### ISSUE TITLE
eunit tests fail on Ubuntu 16.04

### ISSUE THREAD

**Issue by mathiasertl** [processone/eimp#5]
When running `make test` on Ubuntu 16.04, I get the error from this file: https://sh1.fsinf.at/~mati/eimp.txt

Ubuntu 16.04 has erlang 18.3. The same command works fine on Debian Stable and Ubuntu 17.04/17.10.

**Comment by bowlofeggs** [comment]
I see very similar test failures on Fedora 28 and Rawhide with Erlang 20.

**Comment by Neustradamus** [comment]
@prefiks: Please look here ^

@mathiasertl, @bowlofeggs: Any news on this issue?

**Comment by badlop** [comment]
Those tests work correctly in Travis using Ubunbu Bionic (18.04), which includes libgd-dev 2.2.5.

However, using Ubuntu Xenial (16.04), which includes libgd-dev 2.1.1, provokes that problem, regardless of the Erlang/OTP version. I've checked that in [those personal tests](https://travis-ci.org/github/badlop/eimp/builds/763801964).

So, I'd say that problem may be caused by some old buggy library versions.
